exports.itemFilterJson = require('./filters/totem-item.json')
exports.avatarFilterJson = require('./filters/totem-avatar.json')
exports.assets_abi = require('./ABI/assets_abi.json')
exports.game_directory_abi = require('./ABI/json/TotemGameDirectory.json')
exports.legacy_abi = require('./ABI/json/TotemLegacy.json')
